# Generated by Django 6.0.6 on 2026-06-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
